language: php
php:
  - 5.6

notifications:
  email: false

install:
  - composer install --dev --no-interaction
script:
  - phpunit --configuration .phpunit.xml --verbose
after_script:
  - php vendor/bin/test-reporter
